name: Java CI

on:
  pull_request:
    branches: [ "main"]


jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permission For Gradlew
        run: |
          cd kobaco
          cd kobaco
          chmod +x gradlew

      - name: Build With Gradle
        run: |
          cd kobaco
          cd kobaco
          ./gradlew build